In [1]:
import numpy as np
a = np.random.uniform(10,100,(5,5))
print(a)

[[16.14818026 76.14400937 63.62518266 99.3218449  16.9466232 ]
 [39.48727208 17.59491533 33.72896666 32.7831762  93.4016232 ]
 [46.05216586 75.60526057 30.6241234  66.68401545 65.48511577]
 [11.13876188 40.33324453 48.58633994 85.5888384  13.60490521]
 [69.26099701 25.2609026  47.41762716 25.77952899 63.1665707 ]]


In [2]:
b = np.array(a, dtype='int')
print(b)

[[16 76 63 99 16]
 [39 17 33 32 93]
 [46 75 30 66 65]
 [11 40 48 85 13]
 [69 25 47 25 63]]


In [3]:
print(a.astype(int))

[[16 76 63 99 16]
 [39 17 33 32 93]
 [46 75 30 66 65]
 [11 40 48 85 13]
 [69 25 47 25 63]]


In [4]:
for i in a:
    for j in i:
        print(int(j))

16
76
63
99
16
39
17
33
32
93
46
75
30
66
65
11
40
48
85
13
69
25
47
25
63


In [5]:
print(np.floor(a))

[[16. 76. 63. 99. 16.]
 [39. 17. 33. 32. 93.]
 [46. 75. 30. 66. 65.]
 [11. 40. 48. 85. 13.]
 [69. 25. 47. 25. 63.]]


In [6]:
print(np.trunc(a))

[[16. 76. 63. 99. 16.]
 [39. 17. 33. 32. 93.]
 [46. 75. 30. 66. 65.]
 [11. 40. 48. 85. 13.]
 [69. 25. 47. 25. 63.]]


In [7]:
print(np.rint(a))

[[16. 76. 64. 99. 17.]
 [39. 18. 34. 33. 93.]
 [46. 76. 31. 67. 65.]
 [11. 40. 49. 86. 14.]
 [69. 25. 47. 26. 63.]]


In [8]:
print(np.around(a))

[[16. 76. 64. 99. 17.]
 [39. 18. 34. 33. 93.]
 [46. 76. 31. 67. 65.]
 [11. 40. 49. 86. 14.]
 [69. 25. 47. 26. 63.]]


In [9]:
print(np.ceil(a))

[[ 17.  77.  64. 100.  17.]
 [ 40.  18.  34.  33.  94.]
 [ 47.  76.  31.  67.  66.]
 [ 12.  41.  49.  86.  14.]
 [ 70.  26.  48.  26.  64.]]


In [10]:
print(np.fix(a))

[[16. 76. 63. 99. 16.]
 [39. 17. 33. 32. 93.]
 [46. 75. 30. 66. 65.]
 [11. 40. 48. 85. 13.]
 [69. 25. 47. 25. 63.]]


In [11]:
print(a - a%1)

[[16. 76. 63. 99. 16.]
 [39. 17. 33. 32. 93.]
 [46. 75. 30. 66. 65.]
 [11. 40. 48. 85. 13.]
 [69. 25. 47. 25. 63.]]


In [12]:
c = np.random.randint(5,10,(2,3,3,4))
print (c)
sum = c.sum(axis=(-2,-1))
print("Output:\n",sum)

[[[[9 9 7 8]
   [7 8 5 5]
   [8 8 6 5]]

  [[8 5 8 6]
   [9 9 8 9]
   [8 9 5 6]]

  [[9 9 9 6]
   [9 6 7 8]
   [5 6 5 6]]]


 [[[7 6 7 5]
   [8 6 8 5]
   [9 9 8 5]]

  [[7 6 5 5]
   [7 6 5 6]
   [9 5 8 8]]

  [[8 6 9 7]
   [8 5 8 9]
   [6 5 5 8]]]]
Output:
 [[85 90 85]
 [83 77 84]]


In [13]:
d = np.random.randint(0,3,(2,2))
print("Matrix A:\n",d)
e = np.random.randint(4,8,(2,2))
print("Matrix B:\n",e)
f = np.dot(d,e)
print("Product of A & B:\n",f)
print("Diagonal Output:\n",np.diag(f))

Matrix A:
 [[0 0]
 [2 0]]
Matrix B:
 [[6 5]
 [4 5]]
Product of A & B:
 [[ 0  0]
 [12 10]]
Diagonal Output:
 [ 0 10]


In [14]:
g = np.random.randint(5, 10, 15)
print(g)
h =np.full(g.shape, False)
i = np.unique(ar=g, return_index=True)[1]
h[i] = True
print(h)

[6 7 6 5 9 5 8 8 9 5 8 9 7 5 6]
[ True  True False  True  True False  True False False False False False
 False False False]


In [15]:
j = np.array([[ 10, 1, 22],[ 4, 55, 6],[ 88, 9, 100],[12, 30, 14]])
print("Input:\n",j)
k = np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=j, axis=1)
print("Output:\n",k)

Input:
 [[ 10   1  22]
 [  4  55   6]
 [ 88   9 100]
 [ 12  30  14]]
Output:
 [0.04545455 0.07272727 0.09       0.4       ]


In [16]:
l = np.array([[ 0, 1, 2, 3],[ 4, 5, 6, 7],[ 8, 9, 10, 11],[12, 13, 14, 15]])
print("Input:\n",l)
m = l.flatten()
n = l.flatten('F')
print("Output1:\n",m)
print("Output2:\n",n)

Input:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Output1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Output2:
 [ 0  4  8 12  1  5  9 13  2  6 10 14  3  7 11 15]


In [17]:
o = np.arange(16).reshape(4,4)
print("Original:\n",o)
o[o % 2 == 1] = -10
print("Output:\n",o)
print("Check Original:\n",o)

Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Output:
 [[  0 -10   2 -10]
 [  4 -10   6 -10]
 [  8 -10  10 -10]
 [ 12 -10  14 -10]]
Check Original:
 [[  0 -10   2 -10]
 [  4 -10   6 -10]
 [  8 -10  10 -10]
 [ 12 -10  14 -10]]


In [18]:
p = np.arange(32,48).reshape(4,4)
print("Original:\n",p)
q = np.where(p % 2 == 1, -10, p)
print("Output:\n",q)
print("Check Original:\n",p)

Original:
 [[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
Output:
 [[ 32 -10  34 -10]
 [ 36 -10  38 -10]
 [ 40 -10  42 -10]
 [ 44 -10  46 -10]]
Check Original:
 [[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]


In [19]:
r = np.array([1,2,3])
s = np.repeat(r, 4)
t = np.array([1, 2, 3])
u = np.tile(t, 4)
v = np.concatenate((s,u), axis=None)
print(v)

[1 1 1 1 2 2 2 2 3 3 3 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [20]:
start = 15
length = 100
step = 3
stop = start+(step*length)
w = np.arange(start,stop,step)
print(w)

[ 15  18  21  24  27  30  33  36  39  42  45  48  51  54  57  60  63  66
  69  72  75  78  81  84  87  90  93  96  99 102 105 108 111 114 117 120
 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174
 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228
 231 234 237 240 243 246 249 252 255 258 261 264 267 270 273 276 279 282
 285 288 291 294 297 300 303 306 309 312]


In [21]:
P = np.array([[ 10, 1, 22, 3],[ 4, 55, 1, 70]])
Q = np.array([[ 0, 1, 100, 3],[4, 37, 1, 55]])
position = np.where(P == Q)[1]
print(position)

[1 3 0 2]


In [22]:
x = np.random.uniform(low=50, high=100,size=(2,2))
print("Input",x)
y = np.flip(x, 0)
print("Row swapping:\n",y)
#z=np.flipud(x)
z=np.flipud(y)
print("Reverse columns:\n",z)

Input [[75.7743717  68.43432862]
 [70.69653515 50.98920072]]
Row swapping:
 [[70.69653515 50.98920072]
 [75.7743717  68.43432862]]
Reverse columns:
 [[75.7743717  68.43432862]
 [70.69653515 50.98920072]]


In [23]:
A = np.random.uniform(low=50, high=100,size=(4,4))
print(A)

[[50.98933223 89.08949885 76.33298955 88.13258464]
 [87.15581887 66.9680999  82.89112262 75.45217353]
 [64.67231672 98.14325175 85.01532432 66.18427518]
 [76.87903758 75.96044775 58.87597942 96.68618036]]


In [24]:
import sys
B = np.random.uniform(low=1, high=50,size=(100,100))
np.set_printoptions(precision=4,threshold=sys.maxsize)
B

array([[ 6.1043,  2.2563, 21.8527, 10.0358, 41.0322, 23.0791, 38.5983,
         1.4728, 27.783 ,  6.2299, 49.6126, 25.689 ,  3.0975,  2.9043,
        37.7563, 47.9505,  9.4629, 42.3081, 17.2533, 38.212 , 28.3877,
         8.304 , 23.4373, 20.5176, 15.5286, 18.4027, 32.5819, 36.3344,
        15.5517, 17.1921, 40.1729,  8.0007, 12.6612, 42.1846,  3.724 ,
        15.1969,  7.7796, 15.3776, 25.8163, 15.5546, 38.5129, 16.881 ,
        28.5691, 26.7201, 11.3694, 19.4268, 11.567 , 12.5631, 15.2143,
        41.8046, 45.3118, 31.5602,  8.442 , 18.2824,  6.0918, 22.2036,
        13.7822, 33.65  , 11.3352, 20.1317, 18.0701, 37.5856, 37.5834,
        35.4642, 28.1057, 37.9931, 45.5318, 36.9604, 39.0773, 20.9972,
        32.9128, 30.8823, 14.3948, 29.5755, 45.8457,  8.7124, 41.5751,
        35.1092,  1.6899, 15.6013, 45.4288, 31.8652, 37.6079, 17.7204,
        31.1853, 36.9885, 13.7735, 16.831 ,  6.7434, 49.5789,  4.3961,
        11.933 , 11.1665,  1.9331, 21.6881, 19.752 , 13.378 ,  4.222 ,
      

In [25]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_2d = np.genfromtxt(url, dtype= "object", delimiter= ",")
# ["Sepallength" "sepelwidth" "petallength" "petalwidth" "species"]
iris_2d

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

In [26]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_2d = np.genfromtxt(url, dtype= "float", delimiter= ",", usecols=[0,1,2,3])
# ["Sepallength" "sepelwidth" "petallength" "petalwidth"]
Filter = (iris_2d[:, 0] < 5.0) & (iris_2d[:, 2] > 1.5)  
iris_2d[Filter]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [27]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
sepallength = np.genfromtxt(url, dtype= "float", delimiter= ",", usecols=[0])
# ["Sepallength"]
sepallength
ma = np.amax(sepallength)
mi = np.amin(sepallength)
nor = ((sepallength)-(mi))/((ma)-(mi))
print(nor)

[0.2222 0.1667 0.1111 0.0833 0.1944 0.3056 0.0833 0.1944 0.0278 0.1667
 0.3056 0.1389 0.1389 0.     0.4167 0.3889 0.3056 0.2222 0.3889 0.2222
 0.3056 0.2222 0.0833 0.2222 0.1389 0.1944 0.1944 0.25   0.25   0.1111
 0.1389 0.3056 0.25   0.3333 0.1667 0.1944 0.3333 0.1667 0.0278 0.2222
 0.1944 0.0556 0.0278 0.1944 0.2222 0.1389 0.2222 0.0833 0.2778 0.1944
 0.75   0.5833 0.7222 0.3333 0.6111 0.3889 0.5556 0.1667 0.6389 0.25
 0.1944 0.4444 0.4722 0.5    0.3611 0.6667 0.3611 0.4167 0.5278 0.3611
 0.4444 0.5    0.5556 0.5    0.5833 0.6389 0.6944 0.6667 0.4722 0.3889
 0.3333 0.3333 0.4167 0.4722 0.3056 0.4722 0.6667 0.5556 0.3611 0.3333
 0.3333 0.5    0.4167 0.1944 0.3611 0.3889 0.3889 0.5278 0.2222 0.3889
 0.5556 0.4167 0.7778 0.5556 0.6111 0.9167 0.1667 0.8333 0.6667 0.8056
 0.6111 0.5833 0.6944 0.3889 0.4167 0.5833 0.6111 0.9444 0.9444 0.4722
 0.7222 0.3611 0.9444 0.5556 0.6667 0.8056 0.5278 0.5    0.5833 0.8056
 0.8611 1.     0.5833 0.5556 0.5    0.9444 0.5556 0.5833 0.4722 0.7222
 0.6667 

In [28]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_2d = np.genfromtxt(url, dtype= "object", delimiter= ",")
# ["Sepallength" "sepelwidth" "petallength" "petalwidth" "species"]
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
space = (np.pi * petallength * (sepallength**3))/4
space = space[:, np.newaxis]
up_iris_2d = np.hstack([iris_2d, space])
up_iris_2d

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        145.85739248196884],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        129.36183193576497],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa',
        106.00511157393726],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        114.67127344868102],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        137.44467859455344],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa',
        210.2422918820669],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa',
        107.02652188543561],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa',
        147.26215563702155],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa',
        93.66470001118756],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa',
        138.6019627883196],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa',
        185.50790460182372],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa',
        138.

In [29]:
C = np.random.randint(5, 10, 15)
print(C)
(C[:, None]== np.unique(ar=C)).view(np.int8)

[5 5 8 9 8 7 8 6 7 9 6 8 6 8 7]


array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [30]:
from PIL import Image
from urllib.request import urlopen
URL = "https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg"
pilimg = Image.open(urlopen(URL))
numarr = np.array(pilimg)
print(numarr)

[[[  9  72 125]
  [  9  72 125]
  [  9  72 125]
  [ 10  73 126]
  [ 10  73 126]
  [ 11  74 127]
  [ 11  74 127]
  [ 11  74 127]
  [ 10  73 126]
  [ 10  73 126]
  [ 10  73 126]
  [ 10  73 126]
  [ 10  73 126]
  [ 10  73 126]
  [ 10  73 126]
  [ 10  73 126]
  [ 10  73 126]
  [ 10  73 126]
  [ 11  74 127]
  [ 12  75 128]
  [ 13  76 129]
  [ 13  76 129]
  [ 14  77 130]
  [ 15  78 131]
  [ 12  73 127]
  [ 12  73 127]
  [ 12  73 127]
  [ 13  74 128]
  [ 13  74 128]
  [ 14  75 129]
  [ 14  75 129]
  [ 14  75 129]
  [ 16  77 131]
  [ 15  76 130]
  [ 15  76 130]
  [ 14  75 129]
  [ 14  75 129]
  [ 13  74 128]
  [ 13  74 128]
  [ 12  73 127]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 12  75 126]
  [ 11  74 125]
  [ 11  74 125]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 15  78 129]
  [ 15  78 129]
  [ 15  78 129]
  [ 15  78 129]
  [ 15  78 129]
  [ 15  78 129]
  [ 15  

In [31]:
A = np.random.randint(0,5,(6,4))
print(A)
B = np.random.randint(0,5,(4,2))
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((2,1)).all(1))[0]
print(rows)

[[4 3 3 4]
 [1 4 3 3]
 [3 1 1 1]
 [2 1 3 1]
 [2 3 2 2]
 [1 3 1 2]]
[[0 3]
 [0 1]
 [1 3]
 [0 4]]
[1 2 3 5]


In [32]:
D = np.arange(64*64).reshape(64,64)
print("Original:\n",D)
E = np.add.reduceat(np.add.reduceat(D, np.arange(0, D.shape[0], 16), axis=0),np.arange(0, D.shape[1], 16), axis=1)
print("Output:\n",E)

Original:
 [[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19   20   21   22   23   24   25   26   27
    28   29   30   31   32   33   34   35   36   37   38   39   40   41
    42   43   44   45   46   47   48   49   50   51   52   53   54   55
    56   57   58   59   60   61   62   63]
 [  64   65   66   67   68   69   70   71   72   73   74   75   76   77
    78   79   80   81   82   83   84   85   86   87   88   89   90   91
    92   93   94   95   96   97   98   99  100  101  102  103  104  105
   106  107  108  109  110  111  112  113  114  115  116  117  118  119
   120  121  122  123  124  125  126  127]
 [ 128  129  130  131  132  133  134  135  136  137  138  139  140  141
   142  143  144  145  146  147  148  149  150  151  152  153  154  155
   156  157  158  159  160  161  162  163  164  165  166  167  168  169
   170  171  172  173  174  175  176  177  178  179  180  181  182  183
   184  185  186  187  188  189  190  1

In [33]:
F = np.random.randint(0,5,(20,3))
print("Input:\n",F)
G = F[F.max(axis=1) != F.min(axis=1)]
print("Output:\n",G)

Input:
 [[4 2 3]
 [0 1 0]
 [4 0 0]
 [2 3 4]
 [2 1 1]
 [0 2 2]
 [2 3 0]
 [1 0 3]
 [3 3 0]
 [4 4 2]
 [0 3 3]
 [1 3 2]
 [1 4 0]
 [3 2 0]
 [1 4 1]
 [3 1 1]
 [0 2 0]
 [4 0 2]
 [0 2 3]
 [1 1 3]]
Output:
 [[4 2 3]
 [0 1 0]
 [4 0 0]
 [2 3 4]
 [2 1 1]
 [0 2 2]
 [2 3 0]
 [1 0 3]
 [3 3 0]
 [4 4 2]
 [0 3 3]
 [1 3 2]
 [1 4 0]
 [3 2 0]
 [1 4 1]
 [3 1 1]
 [0 2 0]
 [4 0 2]
 [0 2 3]
 [1 1 3]]


In [34]:
H = np.arange(4*4).reshape(4,4)
print("Original:\n",H)
I = np.arange(4*1).reshape(4,1)
print("Original:\n",I)
J = np.dot(H, I)
print("Output:\n",J)

Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Original:
 [[0]
 [1]
 [2]
 [3]]
Output:
 [[14]
 [38]
 [62]
 [86]]
