# Linear Algebra Basics

* In data science, Knowledge of <code>linear algebra</code> is essential in order to solve and find the values of the variables according to the given problem.
* The data is generally represented as set of <code>linear equations</code> and then transformed to matrices/vectors.
* <code>Visualisation</code> of linear algebra problem helps to understand the data.
* As the <code>number of variables</code> in the given problem increases it takes more time and efforts to find a slution.
* <code>Matrices</code> is powerful tool to solve higher dimensional problems.

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1,2,3,4],[2,4,6,8],[3,6,9,12],[4,8,12,16]])
a

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [3]:
a[0][0]

1

In [4]:
a[1][1]

4

In [5]:
a[2][2]

9

In [6]:
a[3][3]

16

In [7]:
# Shape of matrix "a"
a.shape

(4, 4)

<code>order of matrix "a"</code>: 4*4

<code>Square matrix "a"</code>: Number of rows = Number of columns


In [8]:
b = np.arange(4*4).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.diag(b)

array([ 0,  5, 10, 15])

In [10]:
np.diag(np.diag(b))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

Above matrix is  <code>Square matrix</code> and <code>Diagonal matrix</code>.

In [11]:
# Upper triangular matrix
np.triu(b)

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 0,  0, 10, 11],
       [ 0,  0,  0, 15]])

In [12]:
# Lower triangular matrix
np.tril(b)

array([[ 0,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 8,  9, 10,  0],
       [12, 13, 14, 15]])

In [13]:
# Transpose of matrix
b.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [14]:
# Determinent of matrix
np.linalg.det(b)

-2.9582283945787796e-30

In [15]:
# Trace of matrix
np.trace(b)

30

In [16]:
# Scalar multiplication
c = 2
np.multiply(c,b)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [17]:
i =  np.arange(3*3).reshape(3,3)
j =  np.ones((3,3))

In [18]:
i

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
j

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Matrix addition
np.add(i,j)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [21]:
# Matrix substraction
np.subtract(i,j)

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [22]:
# Matrix scalar multiplication 
np.multiply(i,j)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [23]:
# Matrix multiplication
np.matmul(i,j)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [24]:
np.dot(i,j)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [25]:
# Matrix inversion
k = np.array([[1,3,3],[1,4,3],[1,3,4]])
l = np.linalg.inv(k)

In [26]:
k

array([[1, 3, 3],
       [1, 4, 3],
       [1, 3, 4]])

In [27]:
l

array([[ 7., -3., -3.],
       [-1.,  1.,  0.],
       [-1.,  0.,  1.]])

In [28]:
np.dot(k,l)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* Matrix multiplication satisfies associative property <code>ABC = (AB)C = A(BC)</code>.
* Matrix multiplication does not satisfies communicative property <code>AB = BC</code>.


In [29]:
k = np.array([[1,3,3],[1,4,3],[1,3,4]])
k

array([[1, 3, 3],
       [1, 4, 3],
       [1, 3, 4]])

In [30]:
# Rank of matrix
np.linalg.matrix_rank(k)

3

Inverse(Matrix) = Adjoint(Matrix) / Determinent(Matrix)

Cofactor matrix = Inverse(Matrix).Transpose * Determinent(Matrix)

Adjoint(Matrix) = cofactor matrix.Transpose 

In [31]:
# Cofactor of matrix
x = np.linalg.inv(k).T * np.linalg.det(k)
x

array([[ 7., -1., -1.],
       [-3.,  1.,  0.],
       [-3.,  0.,  1.]])

In [32]:
# Adjoint Matrix of k (Here equal to inverse matrix of k)
x.T

array([[ 7., -3., -3.],
       [-1.,  1.,  0.],
       [-1.,  0.,  1.]])

In [33]:
# Adjoint Matrix k
np.linalg.inv(k) * np.linalg.det(k)

array([[ 7., -3., -3.],
       [-1.,  1.,  0.],
       [-1.,  0.,  1.]])

*  <code>Orthogonal Matrix</code> Matrix.Transpose = Inverse(Matrix)
i.e.,Matrix.Transpose(Matrix) = (Matrix)Matrix.Transpose = Identidity matrix

In [34]:
# Eigen Values(ev) and Eigen vectors(EV)
ev,EV = np.linalg.eig(k)

In [35]:
ev

array([0.12701665, 7.87298335, 1.        ])

In [36]:
EV

array([[-9.79479905e-01,  5.25274437e-01, -2.53139274e-16],
       [ 1.42511607e-01,  6.01700410e-01, -7.07106781e-01],
       [ 1.42511607e-01,  6.01700410e-01,  7.07106781e-01]])

*  <code>Characteristic equation</code> of a square matrix is given by using trace and determinent of matrix
λ2−λ(Trace(Matrix))+Determinent(Matrix) = 0 or det|(A-λI)| = 0
*  <code>Singular Matrix Vs. Non-singular Matrix</code>: 
    If det(Matrix)==0, it is singular matrix
    if det(Matrix)!=0, it is Non-singular matrix then inverse matrix exits
* <code>Similarity Matrix of A</code>:  Is B if PAP**(-1) = B; where P is Invertible and Non-singular matrix.---application:To find image similarity
* <code>Orthogonal Matrix</code>: Inverse(Matrix) = Transpose(Matrix)
* <code>Diagonal Matrix</code>: Eigen values as diagonal elements
* <code>Model Matrix</code>: Matrix of eigen vectors

## Singular Value Decompostion (SVD)
   applications: Dimensionality reduction, Image compression, Effective data representation in subspace...etc.
   
   __Main Idea__: Decompose a single matrices into Product of 3 Matrices

In [37]:
k = np.array([[1,3,3],[1,4,3],[1,3,4]])
k

array([[1, 3, 3],
       [1, 4, 3],
       [1, 3, 4]])

In [38]:
U, S, Vtranspose = np.linalg.svd(k)

In [39]:
U

array([[-5.20898474e-01, -2.62681588e-16,  8.53618639e-01],
       [-6.03599528e-01, -7.07106781e-01, -3.68330843e-01],
       [-6.03599528e-01,  7.07106781e-01, -3.68330843e-01]])

In [40]:
S

array([8.36574631, 1.        , 0.11953506])

In [41]:
Vtranspose

array([[-0.20656824, -0.69185604, -0.69185604],
       [ 0.        , -0.70710678,  0.70710678],
       [ 0.9784322 , -0.14606581, -0.14606581]])

In [42]:
# Vectors
a = [2,4,8]
b = [3,6,9]

In [43]:
print(a+b)

[2, 4, 8, 3, 6, 9]


In [44]:
# vector addition
c = np.add(a,b)
c

array([ 5, 10, 17])

In [45]:
# Cross product
d = np.cross(a,b)
d

array([-12,   6,   0])

In [46]:
# Dot product
e = np.dot(a,b)
e

102