In [1]:
import math
C=50
H=30
d=input("Enter the comma seperated sequence: ")
D=d.split(",")
new=[]
for i in D:
    Q = new.append(str(int(math.floor(math.sqrt((2 * C * float(i)/H))))))
print("Output: ",",".join(new))

Enter the comma seperated sequence: 100, 150, 180
Output:  18,22,24


In [2]:
i=str(input("Please enter your sequence of words: "))
I=i.split(",")
new=[]
I.sort()
J=new.append(",".join(I))
print("Output: ",",".join(new))

Please enter your sequence of words:  without, hello, bag, world
Output:   bag, hello, without, world


In [3]:
i=str(input("Enter your message: "))
I=i.upper()
print ("Output:",I)

Enter your message: Hello world Practice makes perfect
Output: HELLO WORLD PRACTICE MAKES PERFECT


In [4]:
i=str(input("Please enter your sequence of words: "))
I=i.split(" ")
new=set(I)
print("Output:"," ".join(sorted(new)))

Please enter your sequence of words: hello world and practice makes perfect and hello world again
Output: again and hello makes perfect practice world


In [5]:
i=input("Enter the comma seperated sequence: ")
I=i.split(",")
new=[]
for i in I:
    bin_i=int(i,2)
    if ((bin_i%5)==0):
        new.append(i)
    else:
        continue
    print("Output:" ,",".join(new))

Enter the comma seperated sequence: 0100,0011,1010,1001
Output: 1010


In [6]:
new=[]
for i in range(1000,3001):
    j=str(i)
    if (int(j[0])%2==0 and int(j[1])%2==0 and int(j[2])%2==0 and int(j[3])%2==0):
        new.append(i)
    else:
        continue
print(" ".join(str(new)))

[ 2 0 0 0 ,   2 0 0 2 ,   2 0 0 4 ,   2 0 0 6 ,   2 0 0 8 ,   2 0 2 0 ,   2 0 2 2 ,   2 0 2 4 ,   2 0 2 6 ,   2 0 2 8 ,   2 0 4 0 ,   2 0 4 2 ,   2 0 4 4 ,   2 0 4 6 ,   2 0 4 8 ,   2 0 6 0 ,   2 0 6 2 ,   2 0 6 4 ,   2 0 6 6 ,   2 0 6 8 ,   2 0 8 0 ,   2 0 8 2 ,   2 0 8 4 ,   2 0 8 6 ,   2 0 8 8 ,   2 2 0 0 ,   2 2 0 2 ,   2 2 0 4 ,   2 2 0 6 ,   2 2 0 8 ,   2 2 2 0 ,   2 2 2 2 ,   2 2 2 4 ,   2 2 2 6 ,   2 2 2 8 ,   2 2 4 0 ,   2 2 4 2 ,   2 2 4 4 ,   2 2 4 6 ,   2 2 4 8 ,   2 2 6 0 ,   2 2 6 2 ,   2 2 6 4 ,   2 2 6 6 ,   2 2 6 8 ,   2 2 8 0 ,   2 2 8 2 ,   2 2 8 4 ,   2 2 8 6 ,   2 2 8 8 ,   2 4 0 0 ,   2 4 0 2 ,   2 4 0 4 ,   2 4 0 6 ,   2 4 0 8 ,   2 4 2 0 ,   2 4 2 2 ,   2 4 2 4 ,   2 4 2 6 ,   2 4 2 8 ,   2 4 4 0 ,   2 4 4 2 ,   2 4 4 4 ,   2 4 4 6 ,   2 4 4 8 ,   2 4 6 0 ,   2 4 6 2 ,   2 4 6 4 ,   2 4 6 6 ,   2 4 6 8 ,   2 4 8 0 ,   2 4 8 2 ,   2 4 8 4 ,   2 4 8 6 ,   2 4 8 8 ,   2 6 0 0 ,   2 6 0 2 ,   2 6 0 4 ,   2 6 0 6 ,   2 6 0 8 ,   2 6 2 0 ,   2 6 2 2 ,   2 6 2 4 ,   2 

In [7]:
I=input("Enter your message: ")
n_l=0
n_d=0
for i in I:
    if (i.isalpha()):
        n_l+=1
    elif (i.isdigit()):
        n_d+=1
    else:
        continue
print("LETTERS", n_l)
print("DIGITS", n_d)

Enter your message: hello world! 123 
LETTERS 10
DIGITS 3


In [8]:
I=input("Enter your message: ")
n_uc=0
n_lc=0
for i in I:
    if (i.isupper()):
        n_uc+=1
    elif (i.islower()):
        n_lc+=1
    else:
        continue
print("UPPERCASE", n_uc)
print("LOWECASE", n_lc)

Enter your message: Hello world!
UPPERCASE 1
LOWECASE 9


In [9]:
i=str(input("Enter the value:"))
a1=i*1
a2=i*2
a3=i*3
a4=i*4
result=int(a1)+int(a2)+int(a3)+int(a4)
print("Output:",result)

Enter the value:9
Output: 11106


In [10]:
i=input("Please enter your sequence: ")
I=i.split(",")
out=[]
for i in I:
    if ((int(i)%2)!=0):
        #o=int(i)*int(i)
        #out.append(o)
        out.append(i)
    else:
        continue
print("Output:",",".join(out))

Please enter your sequence: 1,2,3,4,5,6,7,8,9
Output: 1,3,5,7,9


In [11]:
balance=0
while True:
    i=input("Enter input:")
    I=i.split(" ")
    log=I[0]
    amount=int(I[1])
    if(log=="w" or log=="W"):
        balance-=amount
    elif(log=="d" or log=="D"):
        balance+=amount
    else:
        print("Error:WRONG INPUT \nEnter correctly eg. w 100")
        continue
    i=input("Do you wish to continue(Y or N):")
    if (i[0]=="Y" or i[0]=="y"):
        continue
    else:
        print("------Here is your balance------")
        break
print("Balance:",balance)

Enter input:D 300
Do you wish to continue(Y or N):y
Enter input:D 300
Do you wish to continue(Y or N):y
Enter input:W 200
Do you wish to continue(Y or N):y
Enter input:D 100
Do you wish to continue(Y or N):n
------Here is your balance------
Balance: 500


In [12]:
from operator import itemgetter
l=[]
while True:
    i=input("Enter input in name,age,height:")
    if not i:
        break
    I=i.split(",")
    l.append(tuple(I))
priority=itemgetter(0, 1, 2)
o=sorted(l, key=priority)
print(o)

Enter input in name,age,height:Tom,19,80
Enter input in name,age,height:John,20,90
Enter input in name,age,height:Jony,17,91
Enter input in name,age,height:Jony,17,93
Enter input in name,age,height:Json,21,85
Enter input in name,age,height:
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]


In [13]:
import re
p=input("Enter the passwords:")
q=",".join(p.split(","))
r=q.replace(" ", "")
I=r.split(",")
valid=[]
for i in I:
    
    if (len(i) in range(6,13)) and (re.search("[a-z]",i)) and (re.search("[0-9]",i)) and (re.search("[A-Z]",i)) and (re.search("[$#@]",i)):
        o=valid.append(i)
    else:
        continue
    print("Output:",",".join(valid))

Enter the passwords:ABd1234@1, a F1#, 2w3E*, 2We3345
Output: ABd1234@1


In [14]:
initialbal=int(input("Please initial amount:"))
updatedbal=0
print("Welcome to Bank")
while True:
    ia=int(input("please enter 4-digit PIN: "))
    if (ia > 999 and ia <10000 ):
        pass
    else:
        print("Wrong PIN")
        i=input("Do you wish to continue(Y or N):")
        if (i[0]=="Y" or i[0]=="y"):
            continue
        else:
            print("Thank you for Visiting our ATM")
            break
    print("Select your Option\nb---->Balance\nw---->withdrawl\nd---->Deposit\nc---->Cancel")
    ib=input("Please enter your choice: ")  
    if(ib=="b"):
        print("Your Current balance is {} Rupees".format(initialbal))
        pass
    elif(ib=="w"):
        ic=int(input("Please enter the amount to withdrew:"))
        if (ic<=initialbal):
            updatedbal=initialbal-ic
            print("Your Previous balance is {} Rupees".format(initialbal))
            print("Your Current balance is {} Rupees".format(updatedbal))            
            pass
        else:
            print("You account doesnt have sufficient funds")
            continue
    elif(ib=="d"):
        id=int(input("Please enter the amount to deposit:"))
        updatedbal=initialbal+id
        print("Your Previous balance is {} Rupees".format(initialbal))
        print("Your Current balance is {} Rupees".format(updatedbal))
        continue
    elif(ib=="c"):
        print("Thank you for banking with Us")
        break   
print("Collect your card")

Please initial amount:1500
Welcome to Bank
please enter 4-digit PIN: 1234
Select your Option
b---->Balance
w---->withdrawl
d---->Deposit
c---->Cancel
Please enter your choice: d
Please enter the amount to deposit:500
Your Previous balance is 1500 Rupees
Your Current balance is 2000 Rupees
please enter 4-digit PIN: 1234
Select your Option
b---->Balance
w---->withdrawl
d---->Deposit
c---->Cancel
Please enter your choice: c
Thank you for banking with Us
Collect your card


In [15]:
import itertools

# Two 1D-arrays which are sorted in ascending order
A=[0, 2, 3, 6, 11, 13, 14]
B=[1, 4, 5, 7, 8, 9, 10, 12]

# Merge them into a single sorted array C
C = list(itertools.chain(A, B))
print("Output:",sorted(C))

Output: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [16]:
import itertools

#Initialize a list/nested list
l=[[0, 32.0, 25, 77.0], [5, 41.0], [10, 50.0], [15, 59.0], [20, 68.0, 104.0]]

flatl=list(itertools.chain(*l))

#find the total elements in a list / nested list
print("The number of elements in list given: ",len(flatl))

The number of elements in list given:  13


In [17]:
# Initialize a string list
listOfStr = ["hello", "at" , "test" , "this" , "here" , "now" , "message"]

# Convert list string to a dictionary
dictOflist = {i : listOfStr[i] for i in range(0, len(listOfStr))}
print("Output:",dictOflist)

Output: {0: 'hello', 1: 'at', 2: 'test', 3: 'this', 4: 'here', 5: 'now', 6: 'message'}


In [18]:
import numpy as np

# Initialize the dimension of matrix (n)
n=5

# Create matrix n x n
matrix=np.ones((n,n))
print("Output:",matrix)

Output: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# Initialize a list with both string and numeric values 
listOfSi = ["hello", 10 , "test" , 100 , "here" , "now" , 1000]

# Add only numeric values present in the list
listOfi=[ ]
for i in listOfSi:
    if (type(i)==int):
        listOfi.append(i)
    else:
        continue
print("Output:",listOfi)
s=0
for j in range(0,len(listOfi)):
    s+=listOfi[j]
print("Output:",s)

Output: [10, 100, 1000]
Output: 1110


In [20]:
# Initialize a nested list
l = [['40', '20', '10', '30'], ['K', 'I', 'A', '30', '20'], ['10', '30'], ['100'], ['B', 'A', '100']]

# Sort list of lists by the size of sub lists/nested lists
o=sorted(l, key=len)
print("Output:",o)

Output: [['100'], ['10', '30'], ['B', 'A', '100'], ['40', '20', '10', '30'], ['K', 'I', 'A', '30', '20']]


In [21]:
# Initialize a nested list
l = [[10, 20, 30, 40],[30, 40, 60, 70],[20, 30, 40, 60, 70],[30, 40, 80, 90]]
           
# Print the common elements in all sub lists
a=l[0]
b=l[1:]
for ls in b:
    a=(set(a)&set(ls))
print("Output:",list(a)) 

Output: [40, 30]


In [22]:
# Initialize a list of tuples 
list_tuples=[("apple", "banana", "cherry"),("fire","water","air","earth"),("years","months","days","hours","seconds")]
print("Input:",list_tuples)

# Convert list of tuples to list of lists
list_lists=[list(elem) for elem in list_tuples]
print("Output:",list_lists)

Input: [('apple', 'banana', 'cherry'), ('fire', 'water', 'air', 'earth'), ('years', 'months', 'days', 'hours', 'seconds')]
Output: [['apple', 'banana', 'cherry'], ['fire', 'water', 'air', 'earth'], ['years', 'months', 'days', 'hours', 'seconds']]


In [23]:
#  Initialize a list of tuples
l_t=[('A',40),('C',25),('B',40),('D',25),('E',50)]

# Group the tuples by second value
o={}
for i,j in l_t:
    if j in o:
        o[j].append((i, j)) 
    else: 
        o[j] = [(i, j)] 
print("Output:",o)

Output: {40: [('A', 40), ('B', 40)], 25: [('C', 25), ('D', 25)], 50: [('E', 50)]}


In [24]:
# Initialize a list of tuples 
lis_tup=[(11,2,33),(1,222,333),(111,22,3)]  

# Min and maximum value of a particular element position 
mn=list(map(min, zip(*lis_tup)))
mx=list(map(max, zip(*lis_tup)))

print ("The min values index position wise :", mn) 
print ("The max values index position wise :", mx) 

The min values index position wise : [1, 2, 3]
The max values index position wise : [111, 222, 333]


In [25]:
#  Initialize a list of tuples
l_t=[("var","tupl","min","set"),("str","sum","max","tupl"),("min","sum","str","set"),("tupl","var","max","set")]

# Tuples containing the given element from the list of tuples
i=str(input("enter the element:"))
for ele in l_t:
    if i in ele:
        print("Output:",ele)

enter the element:tupl
Output: ('var', 'tupl', 'min', 'set')
Output: ('str', 'sum', 'max', 'tupl')
Output: ('tupl', 'var', 'max', 'set')


In [26]:
# Initialize a tuple
tup=("E","B1","B2","S1","S2","S3","S4","S5","S6","S7","S8","S9","S10","G")
print(tup)

#  Reverse a tuple
new_tup = tup[::-1]
print("Output:",new_tup)

('E', 'B1', 'B2', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'S10', 'G')
Output: ('G', 'S10', 'S9', 'S8', 'S7', 'S6', 'S5', 'S4', 'S3', 'S2', 'S1', 'B2', 'B1', 'E')


In [27]:
# Create a binary matrix
mat = [[0, 1, 0, 0, 1],  
       [1, 0, 1, 1, 0],  
       [0, 1, 0, 0, 1], 
       [1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0]]

# Print all unique rows of the given matrix
out_mat=[]
for row in mat:
    if row not in out_mat:
        out_mat.append(row)
print("Output:",out_mat)

Output: [[0, 1, 0, 0, 1], [1, 0, 1, 1, 0], [1, 1, 1, 0, 0]]


In [28]:
i_s=str(input("Enter:"))
# Insert the given string in a set 
si_s=set(i_s)
# Check if the string is binary or not
check={'0', '1'}
if (si_s==check or si_s=={'0'} or si_s== {'1'}):
    print("Given input is binary")
else:
    print("Given input is not binary")

Enter:010010110
Given input is binary


In [29]:
# Initialize three array of lists.
list_1=[1, 2, 3, 4, 5, 6, 7, 8]
list_2=[10, 2, 5, 7, 3, 1, 11]
list_3=[8, 7, 2, 15, 4, 3, 12, 1]

# Find common elements in three lists using sets
set_1=set(list_1)
set_2=set(list_2)
set_3=set(list_3)
print("Common elements in three lists:", set_1.intersection(set_2,set_3))

Common elements in three lists: {1, 2, 3, 7}


In [30]:
#  Initialize two array of lists
l1=[1,6,2,3,1,5,6,4]
l2=[8,5,4,6,7,8,4,9]

# Missing and additional values in two lists using sets
print("Mis. values in l1:", list(set(l2).difference(set(l1)))) 
print("Add. values in l1:", list(set(l1).difference(set(l2))))
print("Mis. values in l2:", list(set(l1).difference(set(l2)))) 
print("Add. values in l2:", list(set(l2).difference(set(l1))))

Mis. values in l1: [8, 9, 7]
Add. values in l1: [1, 2, 3]
Mis. values in l2: [1, 2, 3]
Add. values in l2: [8, 9, 7]


In [31]:
# Input as string
i =str(input("Enter text:"))
j = list(i.replace(" ", ""))
# Check whether a given string is Heterogram or not
out=[]
for ele in j:
    if(ele not in out):
        out.append(ele)
        continue
    else:
        print("not a Hetrogram")
        break
if(len(out)==len(j)):
    print("Hetrogram")

Enter text:laptop
not a Hetrogram


In [32]:
i_n=input("Please enter your Text:")
i_n=i_n.lower()
vowels=["a","e","i","o","u"]
i=set(vowels)
out=set([ ])
for element in i_n:
    if element in i:
        out.add(element)
    else:
        pass
if len(out)==len(i):
    print("----------------------")
    print(i_n)
    print("Your input is accepted")
else:
    print("Your input is rejected")

Please enter your Text:Hello lui! Please find me.
----------------------
hello lui! please find me.
Your input is accepted


In [33]:
#  Initialize two sets of strings 
string_set1 = {"abcdefgh","xyz","lmnopqrst","abc"} 
string_set2 = {"ijklmnopqrstuvwxyz","abcdefghijklmnopqrstuvwxyz","defghijklmnopqrstuvwxyz"}

# Pairs of complete strings in two sets after concatenation
a=list(string_set1)
b=list(string_set2)
alphabets=set("abcdefghijklmnopqrstuvwxyz")
o=[]
for i in a:
    for j in b:
        c=i+j
        o.append(c)
for ele in o:
    if (set(ele)==alphabets):
        print(ele)

xyzabcdefghijklmnopqrstuvwxyz
lmnopqrstabcdefghijklmnopqrstuvwxyz
abcabcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
abcdefghabcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
abcdefghdefghijklmnopqrstuvwxyz


In [34]:
# Initialize a dictionary
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25,'Normen':28,'Blanka':20}
print("Dictonary:", Dict)

# Split dictionary keys and values into separate lists
keys, values = zip(*Dict.items())
print("Keys:", list(keys))
print("Values:", list(values))

Dictonary: {'Tim': 18, 'Charlie': 12, 'Tiffany': 22, 'Robert': 25, 'Normen': 28, 'Blanka': 20}
Keys: ['Tim', 'Charlie', 'Tiffany', 'Robert', 'Normen', 'Blanka']
Values: [18, 12, 22, 25, 28, 20]


In [35]:
# Consider two dictionaries
dit1={'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25,'Blanka':20,'Normen':22}
dit2={'Normen':28,'Tom': 15,'Prince':12,'Stiffany':25,'Stark':22,'Blanka':30}

# Common keys between the dictionaries
for key in dit1: 
    if key in dit2:
        print(key)
        continue
    else: 
        pass 

Blanka
Normen


In [36]:
# Initialize a dictionary
d={'Tim': 18, 'Charlie': 12, 'Tiffany': 22, 'Robert': 25, 'Blanka': 50, 'Normen': 50}
print("The original dict:", d)
# Change keys in dictionary
nd=dict()
for key,value in d.items():
    if (value>30):
        nd[key]=value
    else:
        nd["1"+key+"a"]=value
print("The modified keys:", nd)

The original dict: {'Tim': 18, 'Charlie': 12, 'Tiffany': 22, 'Robert': 25, 'Blanka': 50, 'Normen': 50}
The modified keys: {'1Tima': 18, '1Charliea': 12, '1Tiffanya': 22, '1Roberta': 25, 'Blanka': 50, 'Normen': 50}


In [37]:
# Initialize a dictionary
dit={'Tim': 18, 'Charlie': 12, 'Tiffany': 22, 'Robert': 25, 'Normen': 50}
print(dit)

# Change keys in dictionary
invert_dit = dict(map(reversed, dit.items()))
print(invert_dit)

{'Tim': 18, 'Charlie': 12, 'Tiffany': 22, 'Robert': 25, 'Normen': 50}
{18: 'Tim', 12: 'Charlie', 22: 'Tiffany', 25: 'Robert', 50: 'Normen'}


In [38]:
#  Initialize a nested dictionary with numbers as values in sub dictionary
k={"X":{"A":30,"B":15,"C":10},"Y":{"A":35,"B":20,"C":12},"Z":{"A":60,"B":25,"C":5}}

# Sum values for each key in nested dictionary
for i in k:
    o=(i,sum(k[i].values()))
    print(o)

('X', 55)
('Y', 67)
('Z', 90)


In [39]:
# Consider two dictionaries
dit1={'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25,'Blanka':20,'Normen':22}
dit2={'Normen':28,'Tom': 15,'Prince':12,'Tiffany':25,'Stark':22,'Blanka':30}

# Finding difference in keys of two-dictionaries
keys1, values1 = zip(*dit1.items())
k_dit1=set(keys1)
print("Dictionary 1 keys:,",k_dit1)
keys2, values2 = zip(*dit2.items())
k_dit2=set(keys2)
print("Dictionary 2 keys:",k_dit2)
print("Differences in keys of two-dictionaries:",k_dit1 ^ k_dit2)

Dictionary 1 keys:, {'Charlie', 'Normen', 'Robert', 'Tim', 'Tiffany', 'Blanka'}
Dictionary 2 keys: {'Normen', 'Stark', 'Tiffany', 'Blanka', 'Prince', 'Tom'}
Differences in keys of two-dictionaries: {'Stark', 'Tim', 'Prince', 'Charlie', 'Robert', 'Tom'}


In [40]:
# Initialize a dictionary
d={"Green":5, "white":3, "Blue":2, "Black":4}

# Second maximum value in a dictionary
max_value = max(d.values())
a=[ ]
for i in d.values():
    if (i<max_value):
        a.append(i)
print("The second maximum value in dict is: ",max(a))

The second maximum value in dict is:  4
